networks:
  bat-network:
    driver: bridge

services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: ./docker-compose/app/Dockerfile
    image: batcave
    container_name: batcave-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - bat-network

  nginx:
    image: nginx:alpine
    container_name: batcave-nginx
    restart: unless-stopped
    ports:
      - "93:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - bat-network

  db:
    image: mariadb
    container_name: batcave-db
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=batcave
      - MYSQL_USER=thebatclaudio
      - MYSQL_PASSWORD=thebatclaudio
    restart: always
    networks:
      - bat-network
