networks:
  bat-network:
    driver: bridge
  nginx-proxy:
    external: true

volumes:
  app:

services:
  app:
    build:
      context: .
      dockerfile: ./docker-compose/app/Dockerfile
    image: batcave-prod
    container_name: batcave-app
    working_dir: /var/www
    volumes:
      - app:/var/www
    restart: always
    environment:
      APP_ENV: production
    networks:
      - bat-network

  nginx:
    image: nginx:alpine
    container_name: batcave-nginx
    restart: always
    expose:
      - 80
    volumes:
      - app:/var/www:ro
      - ./docker-compose/nginx:/etc/nginx/conf.d
    environment:
      VIRTUAL_HOST: thebatclaud.io
      LETSENCRYPT_HOST: thebatclaud.io
      LETSENCRYPT_EMAIL: hello@thebatclaud.io
    networks:
      - bat-network
      - nginx-proxy
