name: Deploy Laravel Application

on:
  push:
    branches:
      - main  # Adjust to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3' # Specify the PHP version
          extensions: mbstring, bcmath, intl, pdo, sqlite, dom
          tools: composer

      - name: Install dependencies
        run: composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader

      - name: Compile assets
        run: npm install && npm run prod

      - name: Sync files to server
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          mkdir -p ~/.ssh
          echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          rsync -az --exclude='.env' --exclude='storage/*' --exclude='.git*' -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa" ./ $SSH_USERNAME@$SSH_HOST:$DEPLOY_PATH
